import type { ReactNode } from 'react';
import { Area, AreaChart as ReAreaChart, Bar, BarChart as ReBarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, LineChart as ReLineChart, Pie, PieChart as RePieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useUI } from '../../provider';
import { Empty } from '../Empty';
import { Spinner } from '../Spinner';

export interface ChartSeries { dataKey: string; name?: string; color?: string; stackId?: string; yAxisId?: string }
export interface CartesianChartProps { data: Record<string, unknown>[]; series: ChartSeries[]; xKey: string; height?: number; loading?: boolean; showGrid?: boolean; showLegend?: boolean; showTooltip?: boolean; ariaLabel?: string; valueFormatter?: (value: unknown) => ReactNode; barSize?: number; className?: string }
export interface CombinationChartProps extends Omit<CartesianChartProps, 'series'> { barSeries: ChartSeries[]; lineSeries: ChartSeries[]; dualAxis?: boolean }
export interface PieChartProps { data: Record<string, unknown>[]; nameKey: string; valueKey: string; height?: number; loading?: boolean; donut?: boolean; colors?: string[]; showLegend?: boolean; showTooltip?: boolean; ariaLabel?: string; valueFormatter?: (value: unknown) => ReactNode; className?: string }

const palette = ['var(--ui-chart-1)', 'var(--ui-chart-2)', 'var(--ui-chart-3)', 'var(--ui-chart-4)', 'var(--ui-chart-5)'];
function Shell({ loading, empty, height, label, className, children }: { loading?: boolean; empty: boolean; height: number; label: string; className?: string; children: ReactNode }) { return <div className={`ui-chart${className ? ` ${className}` : ''}`} style={{ height }} role="img" aria-label={label}>{loading ? <Spinner /> : empty ? <Empty compact /> : children}</div>; }
function tooltipFormatter(formatter?: (value: unknown) => ReactNode) { return formatter ? (value: unknown) => formatter(value) : undefined; }

function CartesianChart({ kind, data, series, xKey, height = 320, loading, showGrid = true, showLegend = true, showTooltip = true, ariaLabel, valueFormatter, barSize, className }: CartesianChartProps & { kind: 'line' | 'bar' | 'area' }) { const { t } = useUI(); const label = ariaLabel ?? t('chart'); const common = <>{showGrid && <CartesianGrid strokeDasharray="3 3" stroke="var(--ui-color-border)" />}<XAxis dataKey={xKey} /><YAxis />{showTooltip && <Tooltip formatter={tooltipFormatter(valueFormatter)} />}{showLegend && <Legend />}</>; const marks = series.map((item, index) => { const color = item.color ?? palette[index % palette.length]; if (kind === 'bar') return <Bar key={item.dataKey} dataKey={item.dataKey} name={item.name} fill={color} stackId={item.stackId} yAxisId={item.yAxisId} barSize={barSize} radius={[4, 4, 0, 0]} />; if (kind === 'area') return <Area key={item.dataKey} type="monotone" dataKey={item.dataKey} name={item.name} stroke={color} fill={color} fillOpacity={0.18} />; return <Line key={item.dataKey} type="monotone" dataKey={item.dataKey} name={item.name} stroke={color} strokeWidth={2} dot={false} />; }); return <Shell loading={loading} empty={!data.length} height={height} label={label} className={className}><ResponsiveContainer width="100%" height="100%">{kind === 'bar' ? <ReBarChart data={data}>{common}{marks}</ReBarChart> : kind === 'area' ? <ReAreaChart data={data}>{common}{marks}</ReAreaChart> : <ReLineChart data={data}>{common}{marks}</ReLineChart>}</ResponsiveContainer></Shell>; }
export function LineChart(props: CartesianChartProps) { return <CartesianChart {...props} kind="line" />; }
export function BarChart(props: CartesianChartProps) { return <CartesianChart {...props} kind="bar" />; }
export function AreaChart(props: CartesianChartProps) { return <CartesianChart {...props} kind="area" />; }
export function VerticalBarChart(props: CartesianChartProps) { return <BarChart {...props} />; }
export function GroupedBarChart(props: CartesianChartProps) { return <BarChart {...props} />; }
export function StackedBarChart({ series, ...props }: CartesianChartProps) { return <BarChart {...props} series={series.map((item) => ({ ...item, stackId: item.stackId ?? 'stack' }))} />; }
export function HorizontalBarChart({ data, series, xKey, height = 320, loading, showGrid = true, showLegend = true, showTooltip = true, ariaLabel, valueFormatter, barSize, className }: CartesianChartProps) { const { t } = useUI(); return <Shell loading={loading} empty={!data.length} height={height} label={ariaLabel ?? t('horizontalBarChart')} className={className}><ResponsiveContainer width="100%" height="100%"><ReBarChart data={data} layout="vertical">{showGrid && <CartesianGrid strokeDasharray="3 3" stroke="var(--ui-color-border)" />}<XAxis type="number" /><YAxis type="category" dataKey={xKey} width={80} />{showTooltip && <Tooltip formatter={tooltipFormatter(valueFormatter)} />}{showLegend && <Legend />}{series.map((item, index) => <Bar key={item.dataKey} dataKey={item.dataKey} name={item.name} stackId={item.stackId} fill={item.color ?? palette[index % palette.length]} barSize={barSize} radius={[0, 4, 4, 0]} />)}</ReBarChart></ResponsiveContainer></Shell>; }
export function StackedBarLineChart({ data, barSeries, lineSeries, xKey, dualAxis = false, height = 320, loading, showGrid = true, showLegend = true, showTooltip = true, ariaLabel, valueFormatter, barSize, className }: CombinationChartProps) { const { t } = useUI(); return <Shell loading={loading} empty={!data.length} height={height} label={ariaLabel ?? t(dualAxis ? 'dualAxisChart' : 'combinationChart')} className={className}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}>{showGrid && <CartesianGrid strokeDasharray="3 3" stroke="var(--ui-color-border)" />}<XAxis dataKey={xKey} /><YAxis yAxisId="left" />{dualAxis && <YAxis yAxisId="right" orientation="right" />}{showTooltip && <Tooltip formatter={tooltipFormatter(valueFormatter)} />}{showLegend && <Legend />}{barSeries.map((item, index) => <Bar key={item.dataKey} dataKey={item.dataKey} name={item.name} stackId={item.stackId ?? 'stack'} yAxisId={item.yAxisId ?? 'left'} fill={item.color ?? palette[index % palette.length]} barSize={barSize} />)}{lineSeries.map((item, index) => <Line key={item.dataKey} dataKey={item.dataKey} name={item.name} yAxisId={item.yAxisId ?? (dualAxis ? 'right' : 'left')} stroke={item.color ?? palette[(index + barSeries.length) % palette.length]} strokeWidth={2} />)}</ComposedChart></ResponsiveContainer></Shell>; }
export function DualAxisChart(props: CombinationChartProps) { return <StackedBarLineChart {...props} dualAxis />; }
export function PieChart({ data, nameKey, valueKey, height = 320, loading, donut = false, colors = palette, showLegend = true, showTooltip = true, ariaLabel, valueFormatter, className }: PieChartProps) { const { t } = useUI(); return <Shell loading={loading} empty={!data.length} height={height} label={ariaLabel ?? t(donut ? 'donutChart' : 'pieChart')} className={className}><ResponsiveContainer width="100%" height="100%"><RePieChart>{showTooltip && <Tooltip formatter={tooltipFormatter(valueFormatter)} />}{showLegend && <Legend />}<Pie data={data} dataKey={valueKey} nameKey={nameKey} innerRadius={donut ? '55%' : 0} outerRadius="78%" paddingAngle={2}>{data.map((_, index) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie></RePieChart></ResponsiveContainer></Shell>; }
export function DonutChart(props: Omit<PieChartProps, 'donut'>) { return <PieChart {...props} donut />; }
