import type { ProductStatusValue } from "./productStatus";

export type ShopProduct = { subcategoryKey: string; sku: string; imageSku: string; status: ProductStatusValue; name: string; size: string; sizeKey: string; sizeCm: string; sizeLabel: string; type: string; price: number; color: string; craftsmanship: string; photoIncluded: string; material: string; description: string };

// Generated from data/MomentFrame_Product_DB.xlsx by yarn sync:catalog. Do not edit by hand.
export const shopProducts: ShopProduct[] = [
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-07-STAND",
    "imageSku": "IMG-S1-T1-07-STAND",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 10,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-08-STAND",
    "imageSku": "IMG-S1-T1-08-STAND",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-10-STAND",
    "imageSku": "IMG-S1-T1-10-STAND",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 18,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-12-STAND",
    "imageSku": "IMG-S1-T1-12-STAND",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 20,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-14-STAND",
    "imageSku": "IMG-S1-T1-14-STAND",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 26,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-16-WALL",
    "imageSku": "IMG-S1-T1-16-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 40,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-18-WALL",
    "imageSku": "IMG-S1-T1-18-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 46,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-20-WALL",
    "imageSku": "IMG-S1-T1-20-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 41,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-24-WALL",
    "imageSku": "IMG-S1-T1-24-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 57,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-30-WALL",
    "imageSku": "IMG-S1-T1-30-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 90,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-32-WALL",
    "imageSku": "IMG-S1-T1-32-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 88,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-36-WALL",
    "imageSku": "IMG-S1-T1-36-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 99,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-40-WALL",
    "imageSku": "IMG-S1-T1-40-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 126,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-48-WALL",
    "imageSku": "IMG-S1-T1-48-WALL",
    "status": "ready-stock",
    "name": "Frameless Rounded Corner",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 138,
    "color": "Borderless",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-07-STAND",
    "imageSku": "IMG-S2-T1-07-STAND",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 11,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-08-STAND",
    "imageSku": "IMG-S2-T1-08-STAND",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-10-STAND",
    "imageSku": "IMG-S2-T1-10-STAND",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 15,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-12-STAND",
    "imageSku": "IMG-S2-T1-12-STAND",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 19,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-14-STAND",
    "imageSku": "IMG-S2-T1-14-STAND",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 21,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-16-WALL",
    "imageSku": "IMG-S2-T1-16-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 27,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-18-WALL",
    "imageSku": "IMG-S2-T1-18-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 36,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-20-WALL",
    "imageSku": "IMG-S2-T1-20-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 40,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-24-WALL",
    "imageSku": "IMG-S2-T1-24-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 49,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-30-WALL",
    "imageSku": "IMG-S2-T1-30-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 58,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-32-WALL",
    "imageSku": "IMG-S2-T1-32-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 66,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-36-WALL",
    "imageSku": "IMG-S2-T1-36-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 81,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-40-WALL",
    "imageSku": "IMG-S2-T1-40-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 99,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-48-WALL",
    "imageSku": "IMG-S2-T1-48-WALL",
    "status": "ready-stock",
    "name": "White Rounded Border",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 120,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-07-STAND",
    "imageSku": "IMG-S2-T2-07-STAND",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 11,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-08-STAND",
    "imageSku": "IMG-S2-T2-08-STAND",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-10-STAND",
    "imageSku": "IMG-S2-T2-10-STAND",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 15,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-12-STAND",
    "imageSku": "IMG-S2-T2-12-STAND",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 19,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-14-STAND",
    "imageSku": "IMG-S2-T2-14-STAND",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 21,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-16-WALL",
    "imageSku": "IMG-S2-T2-16-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 27,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-18-WALL",
    "imageSku": "IMG-S2-T2-18-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 36,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-20-WALL",
    "imageSku": "IMG-S2-T2-20-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 40,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-24-WALL",
    "imageSku": "IMG-S2-T2-24-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 49,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-30-WALL",
    "imageSku": "IMG-S2-T2-30-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 58,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-32-WALL",
    "imageSku": "IMG-S2-T2-32-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 66,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-36-WALL",
    "imageSku": "IMG-S2-T2-36-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 81,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-40-WALL",
    "imageSku": "IMG-S2-T2-40-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 99,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-48-WALL",
    "imageSku": "IMG-S2-T2-48-WALL",
    "status": "ready-stock",
    "name": "Gold Rounded Border",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 120,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-07-STAND",
    "imageSku": "IMG-S2-T3-07-STAND",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 11,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-08-STAND",
    "imageSku": "IMG-S2-T3-08-STAND",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-10-STAND",
    "imageSku": "IMG-S2-T3-10-STAND",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 15,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-12-STAND",
    "imageSku": "IMG-S2-T3-12-STAND",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 19,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-14-STAND",
    "imageSku": "IMG-S2-T3-14-STAND",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 21,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-16-WALL",
    "imageSku": "IMG-S2-T3-16-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 27,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-18-WALL",
    "imageSku": "IMG-S2-T3-18-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 36,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-20-WALL",
    "imageSku": "IMG-S2-T3-20-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 40,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-24-WALL",
    "imageSku": "IMG-S2-T3-24-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 49,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-30-WALL",
    "imageSku": "IMG-S2-T3-30-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 58,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-32-WALL",
    "imageSku": "IMG-S2-T3-32-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 66,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-36-WALL",
    "imageSku": "IMG-S2-T3-36-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 81,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-40-WALL",
    "imageSku": "IMG-S2-T3-40-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 99,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-48-WALL",
    "imageSku": "IMG-S2-T3-48-WALL",
    "status": "ready-stock",
    "name": "Silver Rounded Border",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 120,
    "color": "Silver",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-07-STAND",
    "imageSku": "IMG-S2-T4-07-STAND",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 11,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-08-STAND",
    "imageSku": "IMG-S2-T4-08-STAND",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-10-STAND",
    "imageSku": "IMG-S2-T4-10-STAND",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 15,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-12-STAND",
    "imageSku": "IMG-S2-T4-12-STAND",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 19,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-14-STAND",
    "imageSku": "IMG-S2-T4-14-STAND",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 22,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-16-WALL",
    "imageSku": "IMG-S2-T4-16-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 28,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-18-WALL",
    "imageSku": "IMG-S2-T4-18-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 36,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-20-WALL",
    "imageSku": "IMG-S2-T4-20-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 40,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-24-WALL",
    "imageSku": "IMG-S2-T4-24-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 61,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-30-WALL",
    "imageSku": "IMG-S2-T4-30-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 58,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-32-WALL",
    "imageSku": "IMG-S2-T4-32-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 66,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-36-WALL",
    "imageSku": "IMG-S2-T4-36-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 81,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-40-WALL",
    "imageSku": "IMG-S2-T4-40-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 99,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-48-WALL",
    "imageSku": "IMG-S2-T4-48-WALL",
    "status": "ready-stock",
    "name": "Black Rounded Border",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 120,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-07-STAND",
    "imageSku": "IMG-S2-T5-07-STAND",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 16,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-08-STAND",
    "imageSku": "IMG-S2-T5-08-STAND",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 24,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-10-STAND",
    "imageSku": "IMG-S2-T5-10-STAND",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 28,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-12-STAND",
    "imageSku": "IMG-S2-T5-12-STAND",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 34,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-14-STAND",
    "imageSku": "IMG-S2-T5-14-STAND",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 36,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-16-WALL",
    "imageSku": "IMG-S2-T5-16-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 45,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-18-WALL",
    "imageSku": "IMG-S2-T5-18-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 47,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-20-WALL",
    "imageSku": "IMG-S2-T5-20-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 53,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-24-WALL",
    "imageSku": "IMG-S2-T5-24-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 72,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-30-WALL",
    "imageSku": "IMG-S2-T5-30-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 95,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-32-WALL",
    "imageSku": "IMG-S2-T5-32-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 117,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-36-WALL",
    "imageSku": "IMG-S2-T5-36-WALL",
    "status": "ready-stock",
    "name": "Black Square Corner",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 128,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-07-STAND",
    "imageSku": "IMG-S2-T6-07-STAND",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 16,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-08-STAND",
    "imageSku": "IMG-S2-T6-08-STAND",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 24,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-10-STAND",
    "imageSku": "IMG-S2-T6-10-STAND",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 28,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-12-STAND",
    "imageSku": "IMG-S2-T6-12-STAND",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "12\"",
    "sizeKey": "12-inch",
    "sizeCm": "20 × 30 cm / 25 × 30 cm",
    "sizeLabel": "12\" (20 × 30 cm / 25 × 30 cm)",
    "type": "Tabletop",
    "price": 34,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-14-STAND",
    "imageSku": "IMG-S2-T6-14-STAND",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "14\"",
    "sizeKey": "14-inch",
    "sizeCm": "25 × 35 cm",
    "sizeLabel": "14\" (25 × 35 cm)",
    "type": "Tabletop",
    "price": 36,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-16-WALL",
    "imageSku": "IMG-S2-T6-16-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "16\"",
    "sizeKey": "16-inch",
    "sizeCm": "30 × 40 cm",
    "sizeLabel": "16\" (30 × 40 cm)",
    "type": "Wall-mounted",
    "price": 45,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-18-WALL",
    "imageSku": "IMG-S2-T6-18-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "18\"",
    "sizeKey": "18-inch",
    "sizeCm": "35 × 45 cm",
    "sizeLabel": "18\" (35 × 45 cm)",
    "type": "Wall-mounted",
    "price": 47,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-20-WALL",
    "imageSku": "IMG-S2-T6-20-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "20\"",
    "sizeKey": "20-inch",
    "sizeCm": "40 × 50 cm",
    "sizeLabel": "20\" (40 × 50 cm)",
    "type": "Wall-mounted",
    "price": 53,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-24-WALL",
    "imageSku": "IMG-S2-T6-24-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 72,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-30-WALL",
    "imageSku": "IMG-S2-T6-30-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 95,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-32-WALL",
    "imageSku": "IMG-S2-T6-32-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "32\"",
    "sizeKey": "32-inch",
    "sizeCm": "60 × 80 cm",
    "sizeLabel": "32\" (60 × 80 cm)",
    "type": "Wall-mounted",
    "price": 117,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-36-WALL",
    "imageSku": "IMG-S2-T6-36-WALL",
    "status": "ready-stock",
    "name": "Black Frame with Gold Trim",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 128,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "PVC Material for Photo Studios",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-24-WALL",
    "imageSku": "IMG-S4-T1-24-WALL",
    "status": "ready-stock",
    "name": "Autumn Warm Wood",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 78,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-30-WALL",
    "imageSku": "IMG-S4-T1-30-WALL",
    "status": "ready-stock",
    "name": "Autumn Warm Wood",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 130,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-36-WALL",
    "imageSku": "IMG-S4-T1-36-WALL",
    "status": "ready-stock",
    "name": "Autumn Warm Wood",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 136,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-40-WALL",
    "imageSku": "IMG-S4-T1-40-WALL",
    "status": "ready-stock",
    "name": "Autumn Warm Wood",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 191,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-48-WALL",
    "imageSku": "IMG-S4-T1-48-WALL",
    "status": "ready-stock",
    "name": "Autumn Warm Wood",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-24-WALL",
    "imageSku": "IMG-S4-T2-24-WALL",
    "status": "ready-stock",
    "name": "Linen Grey",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 76,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-30-WALL",
    "imageSku": "IMG-S4-T2-30-WALL",
    "status": "ready-stock",
    "name": "Linen Grey",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 148,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-36-WALL",
    "imageSku": "IMG-S4-T2-36-WALL",
    "status": "ready-stock",
    "name": "Linen Grey",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 147,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-40-WALL",
    "imageSku": "IMG-S4-T2-40-WALL",
    "status": "ready-stock",
    "name": "Linen Grey",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 187,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-48-WALL",
    "imageSku": "IMG-S4-T2-48-WALL",
    "status": "ready-stock",
    "name": "Linen Grey",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 213,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-24-WALL",
    "imageSku": "IMG-S4-T3-24-WALL",
    "status": "ready-stock",
    "name": "Breeze Elegance",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 78,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-30-WALL",
    "imageSku": "IMG-S4-T3-30-WALL",
    "status": "ready-stock",
    "name": "Breeze Elegance",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 130,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-36-WALL",
    "imageSku": "IMG-S4-T3-36-WALL",
    "status": "ready-stock",
    "name": "Breeze Elegance",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 150,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-40-WALL",
    "imageSku": "IMG-S4-T3-40-WALL",
    "status": "ready-stock",
    "name": "Breeze Elegance",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 194,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-48-WALL",
    "imageSku": "IMG-S4-T3-48-WALL",
    "status": "ready-stock",
    "name": "Breeze Elegance",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 213,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-24-WALL",
    "imageSku": "IMG-S4-T4-24-WALL",
    "status": "ready-stock",
    "name": "Time Imprint",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 87,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-36-WALL",
    "imageSku": "IMG-S4-T4-36-WALL",
    "status": "ready-stock",
    "name": "Time Imprint",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 140,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-40-WALL",
    "imageSku": "IMG-S4-T4-40-WALL",
    "status": "ready-stock",
    "name": "Time Imprint",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 181,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-48-WALL",
    "imageSku": "IMG-S4-T4-48-WALL",
    "status": "ready-stock",
    "name": "Time Imprint",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 201,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-24-WALL",
    "imageSku": "IMG-S4-T5-24-WALL",
    "status": "ready-stock",
    "name": "Walnut Poem",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 78,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-30-WALL",
    "imageSku": "IMG-S4-T5-30-WALL",
    "status": "ready-stock",
    "name": "Walnut Poem",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 127,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-36-WALL",
    "imageSku": "IMG-S4-T5-36-WALL",
    "status": "ready-stock",
    "name": "Walnut Poem",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 143,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-40-WALL",
    "imageSku": "IMG-S4-T5-40-WALL",
    "status": "ready-stock",
    "name": "Walnut Poem",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 181,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-48-WALL",
    "imageSku": "IMG-S4-T5-48-WALL",
    "status": "ready-stock",
    "name": "Walnut Poem",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-24-WALL",
    "imageSku": "IMG-S4-T6-24-WALL",
    "status": "ready-stock",
    "name": "Golden Sand Walnut",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 76,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-30-WALL",
    "imageSku": "IMG-S4-T6-30-WALL",
    "status": "ready-stock",
    "name": "Golden Sand Walnut",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 124,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-36-WALL",
    "imageSku": "IMG-S4-T6-36-WALL",
    "status": "ready-stock",
    "name": "Golden Sand Walnut",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 140,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-40-WALL",
    "imageSku": "IMG-S4-T6-40-WALL",
    "status": "ready-stock",
    "name": "Golden Sand Walnut",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-48-WALL",
    "imageSku": "IMG-S4-T6-48-WALL",
    "status": "ready-stock",
    "name": "Golden Sand Walnut",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 201,
    "color": "Dark Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-24-WALL",
    "imageSku": "IMG-S4-T7-24-WALL",
    "status": "ready-stock",
    "name": "Moonlight White",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 76,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-30-WALL",
    "imageSku": "IMG-S4-T7-30-WALL",
    "status": "ready-stock",
    "name": "Moonlight White",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 148,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-36-WALL",
    "imageSku": "IMG-S4-T7-36-WALL",
    "status": "ready-stock",
    "name": "Moonlight White",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 147,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-40-WALL",
    "imageSku": "IMG-S4-T7-40-WALL",
    "status": "ready-stock",
    "name": "Moonlight White",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 191,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-48-WALL",
    "imageSku": "IMG-S4-T7-48-WALL",
    "status": "ready-stock",
    "name": "Moonlight White",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 201,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-24-WALL",
    "imageSku": "IMG-S4-T8-24-WALL",
    "status": "ready-stock",
    "name": "Walnut Grain",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 78,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-30-WALL",
    "imageSku": "IMG-S4-T8-30-WALL",
    "status": "ready-stock",
    "name": "Walnut Grain",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 130,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-36-WALL",
    "imageSku": "IMG-S4-T8-36-WALL",
    "status": "ready-stock",
    "name": "Walnut Grain",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 136,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-40-WALL",
    "imageSku": "IMG-S4-T8-40-WALL",
    "status": "ready-stock",
    "name": "Walnut Grain",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 191,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-48-WALL",
    "imageSku": "IMG-S4-T8-48-WALL",
    "status": "ready-stock",
    "name": "Walnut Grain",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-24-WALL",
    "imageSku": "IMG-S4-T9-24-WALL",
    "status": "ready-stock",
    "name": "Premium Silver Grey",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 87,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-30-WALL",
    "imageSku": "IMG-S4-T9-30-WALL",
    "status": "ready-stock",
    "name": "Premium Silver Grey",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 127,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-36-WALL",
    "imageSku": "IMG-S4-T9-36-WALL",
    "status": "ready-stock",
    "name": "Premium Silver Grey",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 140,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-40-WALL",
    "imageSku": "IMG-S4-T9-40-WALL",
    "status": "ready-stock",
    "name": "Premium Silver Grey",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-48-WALL",
    "imageSku": "IMG-S4-T9-48-WALL",
    "status": "ready-stock",
    "name": "Premium Silver Grey",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 201,
    "color": "Grey",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-24-WALL",
    "imageSku": "IMG-S4-T10-24-WALL",
    "status": "ready-stock",
    "name": "Monet Window",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 78,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-30-WALL",
    "imageSku": "IMG-S4-T10-30-WALL",
    "status": "ready-stock",
    "name": "Monet Window",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 124,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-36-WALL",
    "imageSku": "IMG-S4-T10-36-WALL",
    "status": "ready-stock",
    "name": "Monet Window",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 140,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-40-WALL",
    "imageSku": "IMG-S4-T10-40-WALL",
    "status": "ready-stock",
    "name": "Monet Window",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 178,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-48-WALL",
    "imageSku": "IMG-S4-T10-48-WALL",
    "status": "ready-stock",
    "name": "Monet Window",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 181,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-24-WALL",
    "imageSku": "IMG-S4-T11-24-WALL",
    "status": "ready-stock",
    "name": "Ivory White",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 87,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-30-WALL",
    "imageSku": "IMG-S4-T11-30-WALL",
    "status": "ready-stock",
    "name": "Ivory White",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 140,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-36-WALL",
    "imageSku": "IMG-S4-T11-36-WALL",
    "status": "ready-stock",
    "name": "Ivory White",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 160,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-40-WALL",
    "imageSku": "IMG-S4-T11-40-WALL",
    "status": "ready-stock",
    "name": "Ivory White",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-48-WALL",
    "imageSku": "IMG-S4-T11-48-WALL",
    "status": "ready-stock",
    "name": "Ivory White",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 201,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-24-WALL",
    "imageSku": "IMG-S4-T12-24-WALL",
    "status": "ready-stock",
    "name": "Gilded Elegance",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 87,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-30-WALL",
    "imageSku": "IMG-S4-T12-30-WALL",
    "status": "ready-stock",
    "name": "Gilded Elegance",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 130,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-36-WALL",
    "imageSku": "IMG-S4-T12-36-WALL",
    "status": "ready-stock",
    "name": "Gilded Elegance",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 168,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-40-WALL",
    "imageSku": "IMG-S4-T12-40-WALL",
    "status": "ready-stock",
    "name": "Gilded Elegance",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 187,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-48-WALL",
    "imageSku": "IMG-S4-T12-48-WALL",
    "status": "ready-stock",
    "name": "Gilded Elegance",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 213,
    "color": "Gold",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-24-WALL",
    "imageSku": "IMG-S4-T13-24-WALL",
    "status": "ready-stock",
    "name": "Golden Years Frame",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 76,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-30-WALL",
    "imageSku": "IMG-S4-T13-30-WALL",
    "status": "ready-stock",
    "name": "Golden Years Frame",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 133,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-36-WALL",
    "imageSku": "IMG-S4-T13-36-WALL",
    "status": "ready-stock",
    "name": "Golden Years Frame",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 147,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-40-WALL",
    "imageSku": "IMG-S4-T13-40-WALL",
    "status": "ready-stock",
    "name": "Golden Years Frame",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 187,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-48-WALL",
    "imageSku": "IMG-S4-T13-48-WALL",
    "status": "ready-stock",
    "name": "Golden Years Frame",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 191,
    "color": "White",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-24-WALL",
    "imageSku": "IMG-S4-T14-24-WALL",
    "status": "ready-stock",
    "name": "Ink Shadow Time",
    "size": "24\"",
    "sizeKey": "24-small",
    "sizeCm": "40 × 60 cm",
    "sizeLabel": "24\" (40 × 60 cm)",
    "type": "Wall-mounted",
    "price": 87,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-30-WALL",
    "imageSku": "IMG-S4-T14-30-WALL",
    "status": "ready-stock",
    "name": "Ink Shadow Time",
    "size": "30\"",
    "sizeKey": "30-inch",
    "sizeCm": "60 × 75 cm",
    "sizeLabel": "30\" (60 × 75 cm)",
    "type": "Wall-mounted",
    "price": 124,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-36-WALL",
    "imageSku": "IMG-S4-T14-36-WALL",
    "status": "ready-stock",
    "name": "Ink Shadow Time",
    "size": "36\"",
    "sizeKey": "36-inch",
    "sizeCm": "60 × 90 cm",
    "sizeLabel": "36\" (60 × 90 cm)",
    "type": "Wall-mounted",
    "price": 160,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-40-WALL",
    "imageSku": "IMG-S4-T14-40-WALL",
    "status": "ready-stock",
    "name": "Ink Shadow Time",
    "size": "40\"",
    "sizeKey": "40-inch",
    "sizeCm": "75 × 100 cm",
    "sizeLabel": "40\" (75 × 100 cm)",
    "type": "Wall-mounted",
    "price": 177,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-48-WALL",
    "imageSku": "IMG-S4-T14-48-WALL",
    "status": "ready-stock",
    "name": "Ink Shadow Time",
    "size": "48\"",
    "sizeKey": "48-inch",
    "sizeCm": "75 × 120 cm",
    "sizeLabel": "48\" (75 × 120 cm)",
    "type": "Wall-mounted",
    "price": 201,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-06-NOT SET",
    "imageSku": "IMG-S3-T1-06-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Vintage Walnut",
    "size": "6\"",
    "sizeKey": "6-inch",
    "sizeCm": "10.2 × 15.2 cm",
    "sizeLabel": "6\" (10.2 × 15.2 cm)",
    "type": "Tabletop",
    "price": 14,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-07-NOT SET",
    "imageSku": "IMG-S3-T1-07-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Vintage Walnut",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 18,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-08-NOT SET",
    "imageSku": "IMG-S3-T1-08-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Vintage Walnut",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 20,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-10-NOT SET",
    "imageSku": "IMG-S3-T1-10-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Vintage Walnut",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 26,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-04-NOT SET",
    "imageSku": "IMG-S3-T1-04-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Vintage Walnut",
    "size": "A4",
    "sizeKey": "a4",
    "sizeCm": "21 × 29.7 cm",
    "sizeLabel": "A4 (21 × 29.7 cm)",
    "type": "Tabletop",
    "price": 30,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-03-NOT SET",
    "imageSku": "IMG-S3-T1-03-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Vintage Walnut",
    "size": "A3",
    "sizeKey": "a3",
    "sizeCm": "29.7 × 42 cm",
    "sizeLabel": "A3 (29.7 × 42 cm)",
    "type": "Tabletop",
    "price": 39,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-06-NOT SET",
    "imageSku": "IMG-S3-T2-06-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Warm Walnut",
    "size": "6\"",
    "sizeKey": "6-inch",
    "sizeCm": "10.2 × 15.2 cm",
    "sizeLabel": "6\" (10.2 × 15.2 cm)",
    "type": "Tabletop",
    "price": 14,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-07-NOT SET",
    "imageSku": "IMG-S3-T2-07-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Warm Walnut",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 18,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-08-NOT SET",
    "imageSku": "IMG-S3-T2-08-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Warm Walnut",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 20,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-10-NOT SET",
    "imageSku": "IMG-S3-T2-10-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Warm Walnut",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 26,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-04-NOT SET",
    "imageSku": "IMG-S3-T2-04-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Warm Walnut",
    "size": "A4",
    "sizeKey": "a4",
    "sizeCm": "21 × 29.7 cm",
    "sizeLabel": "A4 (21 × 29.7 cm)",
    "type": "Tabletop",
    "price": 30,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-03-NOT SET",
    "imageSku": "IMG-S3-T2-03-NOT SET",
    "status": "ready-stock",
    "name": "Solid Wood - Warm Walnut",
    "size": "A3",
    "sizeKey": "a3",
    "sizeCm": "29.7 × 42 cm",
    "sizeLabel": "A3 (29.7 × 42 cm)",
    "type": "Tabletop",
    "price": 39,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-06-NOT SET",
    "imageSku": "IMG-S3-T3-06-NOT SET",
    "status": "ready-stock",
    "name": "Fresh Light Wheat",
    "size": "6\"",
    "sizeKey": "6-inch",
    "sizeCm": "10.2 × 15.2 cm",
    "sizeLabel": "6\" (10.2 × 15.2 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-07-NOT SET",
    "imageSku": "IMG-S3-T3-07-NOT SET",
    "status": "ready-stock",
    "name": "Fresh Light Wheat",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 14,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-08-NOT SET",
    "imageSku": "IMG-S3-T3-08-NOT SET",
    "status": "ready-stock",
    "name": "Fresh Light Wheat",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 18,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-10-NOT SET",
    "imageSku": "IMG-S3-T3-10-NOT SET",
    "status": "ready-stock",
    "name": "Fresh Light Wheat",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 26,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-04-NOT SET",
    "imageSku": "IMG-S3-T3-04-NOT SET",
    "status": "ready-stock",
    "name": "Fresh Light Wheat",
    "size": "A4",
    "sizeKey": "a4",
    "sizeCm": "21 × 29.7 cm",
    "sizeLabel": "A4 (21 × 29.7 cm)",
    "type": "Tabletop",
    "price": 30,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-03-NOT SET",
    "imageSku": "IMG-S3-T3-03-NOT SET",
    "status": "ready-stock",
    "name": "Fresh Light Wheat",
    "size": "A3",
    "sizeKey": "a3",
    "sizeCm": "29.7 × 42 cm",
    "sizeLabel": "A3 (29.7 × 42 cm)",
    "type": "Tabletop",
    "price": 39,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-06-NOT SET",
    "imageSku": "IMG-S3-T4-06-NOT SET",
    "status": "ready-stock",
    "name": "Roasted Tea",
    "size": "6\"",
    "sizeKey": "6-inch",
    "sizeCm": "10.2 × 15.2 cm",
    "sizeLabel": "6\" (10.2 × 15.2 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-07-NOT SET",
    "imageSku": "IMG-S3-T4-07-NOT SET",
    "status": "ready-stock",
    "name": "Roasted Tea",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 14,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-08-NOT SET",
    "imageSku": "IMG-S3-T4-08-NOT SET",
    "status": "ready-stock",
    "name": "Roasted Tea",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 18,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-10-NOT SET",
    "imageSku": "IMG-S3-T4-10-NOT SET",
    "status": "ready-stock",
    "name": "Roasted Tea",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 26,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-04-NOT SET",
    "imageSku": "IMG-S3-T4-04-NOT SET",
    "status": "ready-stock",
    "name": "Roasted Tea",
    "size": "A4",
    "sizeKey": "a4",
    "sizeCm": "21 × 29.7 cm",
    "sizeLabel": "A4 (21 × 29.7 cm)",
    "type": "Tabletop",
    "price": 30,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-03-NOT SET",
    "imageSku": "IMG-S3-T4-03-NOT SET",
    "status": "ready-stock",
    "name": "Roasted Tea",
    "size": "A3",
    "sizeKey": "a3",
    "sizeCm": "29.7 × 42 cm",
    "sizeLabel": "A3 (29.7 × 42 cm)",
    "type": "Tabletop",
    "price": 39,
    "color": "Brown",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-06-NOT SET",
    "imageSku": "IMG-S3-T5-06-NOT SET",
    "status": "ready-stock",
    "name": "Black Walnut",
    "size": "6\"",
    "sizeKey": "6-inch",
    "sizeCm": "10.2 × 15.2 cm",
    "sizeLabel": "6\" (10.2 × 15.2 cm)",
    "type": "Tabletop",
    "price": 13,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-07-NOT SET",
    "imageSku": "IMG-S3-T5-07-NOT SET",
    "status": "ready-stock",
    "name": "Black Walnut",
    "size": "7\"",
    "sizeKey": "7-inch",
    "sizeCm": "12.7 × 17.8 cm",
    "sizeLabel": "7\" (12.7 × 17.8 cm)",
    "type": "Tabletop",
    "price": 14,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-08-NOT SET",
    "imageSku": "IMG-S3-T5-08-NOT SET",
    "status": "ready-stock",
    "name": "Black Walnut",
    "size": "8\"",
    "sizeKey": "8-inch",
    "sizeCm": "15 × 20 cm",
    "sizeLabel": "8\" (15 × 20 cm)",
    "type": "Tabletop",
    "price": 18,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-10-NOT SET",
    "imageSku": "IMG-S3-T5-10-NOT SET",
    "status": "ready-stock",
    "name": "Black Walnut",
    "size": "10\"",
    "sizeKey": "10-inch",
    "sizeCm": "18 × 27 cm / 20 × 25 cm",
    "sizeLabel": "10\" (18 × 27 cm / 20 × 25 cm)",
    "type": "Tabletop",
    "price": 26,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-04-NOT SET",
    "imageSku": "IMG-S3-T5-04-NOT SET",
    "status": "ready-stock",
    "name": "Black Walnut",
    "size": "A4",
    "sizeKey": "a4",
    "sizeCm": "21 × 29.7 cm",
    "sizeLabel": "A4 (21 × 29.7 cm)",
    "type": "Tabletop",
    "price": 30,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-03-NOT SET",
    "imageSku": "IMG-S3-T5-03-NOT SET",
    "status": "ready-stock",
    "name": "Black Walnut",
    "size": "A3",
    "sizeKey": "a3",
    "sizeCm": "29.7 × 42 cm",
    "sizeLabel": "A3 (29.7 × 42 cm)",
    "type": "Tabletop",
    "price": 39,
    "color": "Black",
    "craftsmanship": "Lamination",
    "photoIncluded": "Yes",
    "material": "Solid Wood",
    "description": ""
  }
];

export function getProductsForSubcategory(subcategoryKey: string) {
  return shopProducts.filter((product) => product.subcategoryKey === subcategoryKey);
}
