export type ShopProduct = { subcategoryKey: string; sku: string; imageSku: string; name: string; size: string; type: string; price: number; color: string; craftsmanship: string; photoIncluded: string; material: string; description: string };

// Generated from data/MomentFrame_Product_DB.xlsx by yarn sync:catalog. Do not edit by hand.
export const shopProducts: ShopProduct[] = [
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-07-STAND",
    "imageSku": "IMG-S1-T1-07-STAND",
    "name": "Frameless Rounded Corner",
    "size": "7\"",
    "type": "Tabletop",
    "price": 10,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-08-STAND",
    "imageSku": "IMG-S1-T1-08-STAND",
    "name": "Frameless Rounded Corner",
    "size": "8\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-10-STAND",
    "imageSku": "IMG-S1-T1-10-STAND",
    "name": "Frameless Rounded Corner",
    "size": "10\"",
    "type": "Tabletop",
    "price": 18,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-12-STAND",
    "imageSku": "IMG-S1-T1-12-STAND",
    "name": "Frameless Rounded Corner",
    "size": "12\"",
    "type": "Tabletop",
    "price": 20,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-14-STAND",
    "imageSku": "IMG-S1-T1-14-STAND",
    "name": "Frameless Rounded Corner",
    "size": "14\"",
    "type": "Tabletop",
    "price": 26,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-16-WALL",
    "imageSku": "IMG-S1-T1-16-WALL",
    "name": "Frameless Rounded Corner",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 40,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-18-WALL",
    "imageSku": "IMG-S1-T1-18-WALL",
    "name": "Frameless Rounded Corner",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 46,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-20-WALL",
    "imageSku": "IMG-S1-T1-20-WALL",
    "name": "Frameless Rounded Corner",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 41,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-24-WALL",
    "imageSku": "IMG-S1-T1-24-WALL",
    "name": "Frameless Rounded Corner",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 57,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-30-WALL",
    "imageSku": "IMG-S1-T1-30-WALL",
    "name": "Frameless Rounded Corner",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 90,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-32-WALL",
    "imageSku": "IMG-S1-T1-32-WALL",
    "name": "Frameless Rounded Corner",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 88,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-36-WALL",
    "imageSku": "IMG-S1-T1-36-WALL",
    "name": "Frameless Rounded Corner",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 99,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-40-WALL",
    "imageSku": "IMG-S1-T1-40-WALL",
    "name": "Frameless Rounded Corner",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 126,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s1-t1",
    "sku": "MFR-S1-T1-48-WALL",
    "imageSku": "IMG-S1-T1-48-WALL",
    "name": "Frameless Rounded Corner",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 138,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-07-STAND",
    "imageSku": "IMG-S2-T1-07-STAND",
    "name": "White Rounded Border",
    "size": "7\"",
    "type": "Tabletop",
    "price": 11,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-08-STAND",
    "imageSku": "IMG-S2-T1-08-STAND",
    "name": "White Rounded Border",
    "size": "8\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-10-STAND",
    "imageSku": "IMG-S2-T1-10-STAND",
    "name": "White Rounded Border",
    "size": "10\"",
    "type": "Tabletop",
    "price": 15,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-12-STAND",
    "imageSku": "IMG-S2-T1-12-STAND",
    "name": "White Rounded Border",
    "size": "12\"",
    "type": "Tabletop",
    "price": 19,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-14-STAND",
    "imageSku": "IMG-S2-T1-14-STAND",
    "name": "White Rounded Border",
    "size": "14\"",
    "type": "Tabletop",
    "price": 21,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-16-WALL",
    "imageSku": "IMG-S2-T1-16-WALL",
    "name": "White Rounded Border",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 27,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-18-WALL",
    "imageSku": "IMG-S2-T1-18-WALL",
    "name": "White Rounded Border",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 36,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-20-WALL",
    "imageSku": "IMG-S2-T1-20-WALL",
    "name": "White Rounded Border",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 40,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-24-WALL",
    "imageSku": "IMG-S2-T1-24-WALL",
    "name": "White Rounded Border",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 49,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-30-WALL",
    "imageSku": "IMG-S2-T1-30-WALL",
    "name": "White Rounded Border",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 58,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-32-WALL",
    "imageSku": "IMG-S2-T1-32-WALL",
    "name": "White Rounded Border",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 66,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-36-WALL",
    "imageSku": "IMG-S2-T1-36-WALL",
    "name": "White Rounded Border",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 81,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-40-WALL",
    "imageSku": "IMG-S2-T1-40-WALL",
    "name": "White Rounded Border",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 99,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t1",
    "sku": "MFR-S2-T1-48-WALL",
    "imageSku": "IMG-S2-T1-48-WALL",
    "name": "White Rounded Border",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 120,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-07-STAND",
    "imageSku": "IMG-S2-T2-07-STAND",
    "name": "Gold Rounded Border",
    "size": "7\"",
    "type": "Tabletop",
    "price": 11,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-08-STAND",
    "imageSku": "IMG-S2-T2-08-STAND",
    "name": "Gold Rounded Border",
    "size": "8\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-10-STAND",
    "imageSku": "IMG-S2-T2-10-STAND",
    "name": "Gold Rounded Border",
    "size": "10\"",
    "type": "Tabletop",
    "price": 15,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-12-STAND",
    "imageSku": "IMG-S2-T2-12-STAND",
    "name": "Gold Rounded Border",
    "size": "12\"",
    "type": "Tabletop",
    "price": 19,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-14-STAND",
    "imageSku": "IMG-S2-T2-14-STAND",
    "name": "Gold Rounded Border",
    "size": "14\"",
    "type": "Tabletop",
    "price": 21,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-16-WALL",
    "imageSku": "IMG-S2-T2-16-WALL",
    "name": "Gold Rounded Border",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 27,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-18-WALL",
    "imageSku": "IMG-S2-T2-18-WALL",
    "name": "Gold Rounded Border",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 36,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-20-WALL",
    "imageSku": "IMG-S2-T2-20-WALL",
    "name": "Gold Rounded Border",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 40,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-24-WALL",
    "imageSku": "IMG-S2-T2-24-WALL",
    "name": "Gold Rounded Border",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 49,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-30-WALL",
    "imageSku": "IMG-S2-T2-30-WALL",
    "name": "Gold Rounded Border",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 58,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-32-WALL",
    "imageSku": "IMG-S2-T2-32-WALL",
    "name": "Gold Rounded Border",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 66,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-36-WALL",
    "imageSku": "IMG-S2-T2-36-WALL",
    "name": "Gold Rounded Border",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 81,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-40-WALL",
    "imageSku": "IMG-S2-T2-40-WALL",
    "name": "Gold Rounded Border",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 99,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t2",
    "sku": "MFR-S2-T2-48-WALL",
    "imageSku": "IMG-S2-T2-48-WALL",
    "name": "Gold Rounded Border",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 120,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-07-STAND",
    "imageSku": "IMG-S2-T3-07-STAND",
    "name": "Silver Rounded Border",
    "size": "7\"",
    "type": "Tabletop",
    "price": 11,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-08-STAND",
    "imageSku": "IMG-S2-T3-08-STAND",
    "name": "Silver Rounded Border",
    "size": "8\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-10-STAND",
    "imageSku": "IMG-S2-T3-10-STAND",
    "name": "Silver Rounded Border",
    "size": "10\"",
    "type": "Tabletop",
    "price": 15,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-12-STAND",
    "imageSku": "IMG-S2-T3-12-STAND",
    "name": "Silver Rounded Border",
    "size": "12\"",
    "type": "Tabletop",
    "price": 19,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-14-STAND",
    "imageSku": "IMG-S2-T3-14-STAND",
    "name": "Silver Rounded Border",
    "size": "14\"",
    "type": "Tabletop",
    "price": 21,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-16-WALL",
    "imageSku": "IMG-S2-T3-16-WALL",
    "name": "Silver Rounded Border",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 27,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-18-WALL",
    "imageSku": "IMG-S2-T3-18-WALL",
    "name": "Silver Rounded Border",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 36,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-20-WALL",
    "imageSku": "IMG-S2-T3-20-WALL",
    "name": "Silver Rounded Border",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 40,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-24-WALL",
    "imageSku": "IMG-S2-T3-24-WALL",
    "name": "Silver Rounded Border",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 49,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-30-WALL",
    "imageSku": "IMG-S2-T3-30-WALL",
    "name": "Silver Rounded Border",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 58,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-32-WALL",
    "imageSku": "IMG-S2-T3-32-WALL",
    "name": "Silver Rounded Border",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 66,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-36-WALL",
    "imageSku": "IMG-S2-T3-36-WALL",
    "name": "Silver Rounded Border",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 81,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-40-WALL",
    "imageSku": "IMG-S2-T3-40-WALL",
    "name": "Silver Rounded Border",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 99,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t3",
    "sku": "MFR-S2-T3-48-WALL",
    "imageSku": "IMG-S2-T3-48-WALL",
    "name": "Silver Rounded Border",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 120,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-07-STAND",
    "imageSku": "IMG-S2-T4-07-STAND",
    "name": "Black Rounded Border",
    "size": "7\"",
    "type": "Tabletop",
    "price": 11,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-08-STAND",
    "imageSku": "IMG-S2-T4-08-STAND",
    "name": "Black Rounded Border",
    "size": "8\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-10-STAND",
    "imageSku": "IMG-S2-T4-10-STAND",
    "name": "Black Rounded Border",
    "size": "10\"",
    "type": "Tabletop",
    "price": 15,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-12-STAND",
    "imageSku": "IMG-S2-T4-12-STAND",
    "name": "Black Rounded Border",
    "size": "12\"",
    "type": "Tabletop",
    "price": 19,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-14-STAND",
    "imageSku": "IMG-S2-T4-14-STAND",
    "name": "Black Rounded Border",
    "size": "14\"",
    "type": "Tabletop",
    "price": 22,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-16-WALL",
    "imageSku": "IMG-S2-T4-16-WALL",
    "name": "Black Rounded Border",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 28,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-18-WALL",
    "imageSku": "IMG-S2-T4-18-WALL",
    "name": "Black Rounded Border",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 36,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-20-WALL",
    "imageSku": "IMG-S2-T4-20-WALL",
    "name": "Black Rounded Border",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 40,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-24-WALL",
    "imageSku": "IMG-S2-T4-24-WALL",
    "name": "Black Rounded Border",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 61,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-30-WALL",
    "imageSku": "IMG-S2-T4-30-WALL",
    "name": "Black Rounded Border",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 58,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-32-WALL",
    "imageSku": "IMG-S2-T4-32-WALL",
    "name": "Black Rounded Border",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 66,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-36-WALL",
    "imageSku": "IMG-S2-T4-36-WALL",
    "name": "Black Rounded Border",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 81,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-40-WALL",
    "imageSku": "IMG-S2-T4-40-WALL",
    "name": "Black Rounded Border",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 99,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t4",
    "sku": "MFR-S2-T4-48-WALL",
    "imageSku": "IMG-S2-T4-48-WALL",
    "name": "Black Rounded Border",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 120,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-07-STAND",
    "imageSku": "IMG-S2-T5-07-STAND",
    "name": "Black Square Corner",
    "size": "7\"",
    "type": "Tabletop",
    "price": 16,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-08-STAND",
    "imageSku": "IMG-S2-T5-08-STAND",
    "name": "Black Square Corner",
    "size": "8\"",
    "type": "Tabletop",
    "price": 24,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-10-STAND",
    "imageSku": "IMG-S2-T5-10-STAND",
    "name": "Black Square Corner",
    "size": "10\"",
    "type": "Tabletop",
    "price": 28,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-12-STAND",
    "imageSku": "IMG-S2-T5-12-STAND",
    "name": "Black Square Corner",
    "size": "12\"",
    "type": "Tabletop",
    "price": 34,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-14-STAND",
    "imageSku": "IMG-S2-T5-14-STAND",
    "name": "Black Square Corner",
    "size": "14\"",
    "type": "Tabletop",
    "price": 36,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-16-WALL",
    "imageSku": "IMG-S2-T5-16-WALL",
    "name": "Black Square Corner",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 45,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-18-WALL",
    "imageSku": "IMG-S2-T5-18-WALL",
    "name": "Black Square Corner",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 47,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-20-WALL",
    "imageSku": "IMG-S2-T5-20-WALL",
    "name": "Black Square Corner",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 53,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-24-WALL",
    "imageSku": "IMG-S2-T5-24-WALL",
    "name": "Black Square Corner",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 72,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-30-WALL",
    "imageSku": "IMG-S2-T5-30-WALL",
    "name": "Black Square Corner",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 95,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-32-WALL",
    "imageSku": "IMG-S2-T5-32-WALL",
    "name": "Black Square Corner",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 117,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t5",
    "sku": "MFR-S2-T5-36-WALL",
    "imageSku": "IMG-S2-T5-36-WALL",
    "name": "Black Square Corner",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 128,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-07-STAND",
    "imageSku": "IMG-S2-T6-07-STAND",
    "name": "Gold Square Corner",
    "size": "7\"",
    "type": "Tabletop",
    "price": 16,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-08-STAND",
    "imageSku": "IMG-S2-T6-08-STAND",
    "name": "Gold Square Corner",
    "size": "8\"",
    "type": "Tabletop",
    "price": 24,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-10-STAND",
    "imageSku": "IMG-S2-T6-10-STAND",
    "name": "Gold Square Corner",
    "size": "10\"",
    "type": "Tabletop",
    "price": 28,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-12-STAND",
    "imageSku": "IMG-S2-T6-12-STAND",
    "name": "Gold Square Corner",
    "size": "12\"",
    "type": "Tabletop",
    "price": 34,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-14-STAND",
    "imageSku": "IMG-S2-T6-14-STAND",
    "name": "Gold Square Corner",
    "size": "14\"",
    "type": "Tabletop",
    "price": 36,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-16-WALL",
    "imageSku": "IMG-S2-T6-16-WALL",
    "name": "Gold Square Corner",
    "size": "16\"",
    "type": "Wall-mounted",
    "price": 45,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-18-WALL",
    "imageSku": "IMG-S2-T6-18-WALL",
    "name": "Gold Square Corner",
    "size": "18\"",
    "type": "Wall-mounted",
    "price": 47,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-20-WALL",
    "imageSku": "IMG-S2-T6-20-WALL",
    "name": "Gold Square Corner",
    "size": "20\"",
    "type": "Wall-mounted",
    "price": 53,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-24-WALL",
    "imageSku": "IMG-S2-T6-24-WALL",
    "name": "Gold Square Corner",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 72,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-30-WALL",
    "imageSku": "IMG-S2-T6-30-WALL",
    "name": "Gold Square Corner",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 95,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-32-WALL",
    "imageSku": "IMG-S2-T6-32-WALL",
    "name": "Gold Square Corner",
    "size": "32\"",
    "type": "Wall-mounted",
    "price": 117,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s2-t6",
    "sku": "MFR-S2-T6-36-WALL",
    "imageSku": "IMG-S2-T6-36-WALL",
    "name": "Gold Square Corner",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 128,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-24-WALL",
    "imageSku": "IMG-S4-T1-24-WALL",
    "name": "Autumn Warm Wood",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 78,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-30-WALL",
    "imageSku": "IMG-S4-T1-30-WALL",
    "name": "Autumn Warm Wood",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 130,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-36-WALL",
    "imageSku": "IMG-S4-T1-36-WALL",
    "name": "Autumn Warm Wood",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 136,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-40-WALL",
    "imageSku": "IMG-S4-T1-40-WALL",
    "name": "Autumn Warm Wood",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 191,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t1",
    "sku": "MFR-S4-T1-48-WALL",
    "imageSku": "IMG-S4-T1-48-WALL",
    "name": "Autumn Warm Wood",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-24-WALL",
    "imageSku": "IMG-S4-T2-24-WALL",
    "name": "Linen Grey",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 76,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-30-WALL",
    "imageSku": "IMG-S4-T2-30-WALL",
    "name": "Linen Grey",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 148,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-36-WALL",
    "imageSku": "IMG-S4-T2-36-WALL",
    "name": "Linen Grey",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 147,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-40-WALL",
    "imageSku": "IMG-S4-T2-40-WALL",
    "name": "Linen Grey",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 187,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t2",
    "sku": "MFR-S4-T2-48-WALL",
    "imageSku": "IMG-S4-T2-48-WALL",
    "name": "Linen Grey",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 213,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-24-WALL",
    "imageSku": "IMG-S4-T3-24-WALL",
    "name": "Breeze Elegance",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 78,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-30-WALL",
    "imageSku": "IMG-S4-T3-30-WALL",
    "name": "Breeze Elegance",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 130,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-36-WALL",
    "imageSku": "IMG-S4-T3-36-WALL",
    "name": "Breeze Elegance",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 150,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-40-WALL",
    "imageSku": "IMG-S4-T3-40-WALL",
    "name": "Breeze Elegance",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 194,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t3",
    "sku": "MFR-S4-T3-48-WALL",
    "imageSku": "IMG-S4-T3-48-WALL",
    "name": "Breeze Elegance",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 213,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-24-WALL",
    "imageSku": "IMG-S4-T4-24-WALL",
    "name": "Time Imprint",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 87,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-36-WALL",
    "imageSku": "IMG-S4-T4-36-WALL",
    "name": "Time Imprint",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 140,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-40-WALL",
    "imageSku": "IMG-S4-T4-40-WALL",
    "name": "Time Imprint",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 181,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t4",
    "sku": "MFR-S4-T4-48-WALL",
    "imageSku": "IMG-S4-T4-48-WALL",
    "name": "Time Imprint",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 201,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-24-WALL",
    "imageSku": "IMG-S4-T5-24-WALL",
    "name": "Walnut Poem",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 78,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-30-WALL",
    "imageSku": "IMG-S4-T5-30-WALL",
    "name": "Walnut Poem",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 127,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-36-WALL",
    "imageSku": "IMG-S4-T5-36-WALL",
    "name": "Walnut Poem",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 143,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-40-WALL",
    "imageSku": "IMG-S4-T5-40-WALL",
    "name": "Walnut Poem",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 181,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t5",
    "sku": "MFR-S4-T5-48-WALL",
    "imageSku": "IMG-S4-T5-48-WALL",
    "name": "Walnut Poem",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-24-WALL",
    "imageSku": "IMG-S4-T6-24-WALL",
    "name": "Golden Sand Walnut",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 76,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-30-WALL",
    "imageSku": "IMG-S4-T6-30-WALL",
    "name": "Golden Sand Walnut",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 124,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-36-WALL",
    "imageSku": "IMG-S4-T6-36-WALL",
    "name": "Golden Sand Walnut",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 140,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-40-WALL",
    "imageSku": "IMG-S4-T6-40-WALL",
    "name": "Golden Sand Walnut",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t6",
    "sku": "MFR-S4-T6-48-WALL",
    "imageSku": "IMG-S4-T6-48-WALL",
    "name": "Golden Sand Walnut",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 201,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-24-WALL",
    "imageSku": "IMG-S4-T7-24-WALL",
    "name": "Moonlight White",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 76,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-30-WALL",
    "imageSku": "IMG-S4-T7-30-WALL",
    "name": "Moonlight White",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 148,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-36-WALL",
    "imageSku": "IMG-S4-T7-36-WALL",
    "name": "Moonlight White",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 147,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-40-WALL",
    "imageSku": "IMG-S4-T7-40-WALL",
    "name": "Moonlight White",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 191,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t7",
    "sku": "MFR-S4-T7-48-WALL",
    "imageSku": "IMG-S4-T7-48-WALL",
    "name": "Moonlight White",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 201,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-24-WALL",
    "imageSku": "IMG-S4-T8-24-WALL",
    "name": "Walnut Grain",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 78,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-30-WALL",
    "imageSku": "IMG-S4-T8-30-WALL",
    "name": "Walnut Grain",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 130,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-36-WALL",
    "imageSku": "IMG-S4-T8-36-WALL",
    "name": "Walnut Grain",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 136,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-40-WALL",
    "imageSku": "IMG-S4-T8-40-WALL",
    "name": "Walnut Grain",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 191,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t8",
    "sku": "MFR-S4-T8-48-WALL",
    "imageSku": "IMG-S4-T8-48-WALL",
    "name": "Walnut Grain",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-24-WALL",
    "imageSku": "IMG-S4-T9-24-WALL",
    "name": "Premium Silver Grey",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 87,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-30-WALL",
    "imageSku": "IMG-S4-T9-30-WALL",
    "name": "Premium Silver Grey",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 127,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-36-WALL",
    "imageSku": "IMG-S4-T9-36-WALL",
    "name": "Premium Silver Grey",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 140,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-40-WALL",
    "imageSku": "IMG-S4-T9-40-WALL",
    "name": "Premium Silver Grey",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t9",
    "sku": "MFR-S4-T9-48-WALL",
    "imageSku": "IMG-S4-T9-48-WALL",
    "name": "Premium Silver Grey",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 201,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-24-WALL",
    "imageSku": "IMG-S4-T10-24-WALL",
    "name": "Monet Window",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 78,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-30-WALL",
    "imageSku": "IMG-S4-T10-30-WALL",
    "name": "Monet Window",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 124,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-36-WALL",
    "imageSku": "IMG-S4-T10-36-WALL",
    "name": "Monet Window",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 140,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-40-WALL",
    "imageSku": "IMG-S4-T10-40-WALL",
    "name": "Monet Window",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 178,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t10",
    "sku": "MFR-S4-T10-48-WALL",
    "imageSku": "IMG-S4-T10-48-WALL",
    "name": "Monet Window",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 181,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-24-WALL",
    "imageSku": "IMG-S4-T11-24-WALL",
    "name": "Ivory White",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 87,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-30-WALL",
    "imageSku": "IMG-S4-T11-30-WALL",
    "name": "Ivory White",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 140,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-36-WALL",
    "imageSku": "IMG-S4-T11-36-WALL",
    "name": "Ivory White",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 160,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-40-WALL",
    "imageSku": "IMG-S4-T11-40-WALL",
    "name": "Ivory White",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t11",
    "sku": "MFR-S4-T11-48-WALL",
    "imageSku": "IMG-S4-T11-48-WALL",
    "name": "Ivory White",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 201,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-24-WALL",
    "imageSku": "IMG-S4-T12-24-WALL",
    "name": "Gilded Elegance",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 87,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-30-WALL",
    "imageSku": "IMG-S4-T12-30-WALL",
    "name": "Gilded Elegance",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 130,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-36-WALL",
    "imageSku": "IMG-S4-T12-36-WALL",
    "name": "Gilded Elegance",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 168,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-40-WALL",
    "imageSku": "IMG-S4-T12-40-WALL",
    "name": "Gilded Elegance",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 187,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t12",
    "sku": "MFR-S4-T12-48-WALL",
    "imageSku": "IMG-S4-T12-48-WALL",
    "name": "Gilded Elegance",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 213,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-24-WALL",
    "imageSku": "IMG-S4-T13-24-WALL",
    "name": "Golden Years Frame",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 76,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-30-WALL",
    "imageSku": "IMG-S4-T13-30-WALL",
    "name": "Golden Years Frame",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 133,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-36-WALL",
    "imageSku": "IMG-S4-T13-36-WALL",
    "name": "Golden Years Frame",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 147,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-40-WALL",
    "imageSku": "IMG-S4-T13-40-WALL",
    "name": "Golden Years Frame",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 187,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t13",
    "sku": "MFR-S4-T13-48-WALL",
    "imageSku": "IMG-S4-T13-48-WALL",
    "name": "Golden Years Frame",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 191,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-24-WALL",
    "imageSku": "IMG-S4-T14-24-WALL",
    "name": "Ink Shadow Time",
    "size": "24\"",
    "type": "Wall-mounted",
    "price": 87,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-30-WALL",
    "imageSku": "IMG-S4-T14-30-WALL",
    "name": "Ink Shadow Time",
    "size": "30\"",
    "type": "Wall-mounted",
    "price": 124,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-36-WALL",
    "imageSku": "IMG-S4-T14-36-WALL",
    "name": "Ink Shadow Time",
    "size": "36\"",
    "type": "Wall-mounted",
    "price": 160,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-40-WALL",
    "imageSku": "IMG-S4-T14-40-WALL",
    "name": "Ink Shadow Time",
    "size": "40\"",
    "type": "Wall-mounted",
    "price": 177,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s4-t14",
    "sku": "MFR-S4-T14-48-WALL",
    "imageSku": "IMG-S4-T14-48-WALL",
    "name": "Ink Shadow Time",
    "size": "48\"",
    "type": "Wall-mounted",
    "price": 201,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-06-STAND",
    "imageSku": "IMG-S3-T1-06-STAND",
    "name": "Solid Wood - Vintage Walnut",
    "size": "6\"",
    "type": "Tabletop",
    "price": 14,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-07-STAND",
    "imageSku": "IMG-S3-T1-07-STAND",
    "name": "Solid Wood - Vintage Walnut",
    "size": "7\"",
    "type": "Tabletop",
    "price": 18,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-08-STAND",
    "imageSku": "IMG-S3-T1-08-STAND",
    "name": "Solid Wood - Vintage Walnut",
    "size": "8\"",
    "type": "Tabletop",
    "price": 20,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-10-STAND",
    "imageSku": "IMG-S3-T1-10-STAND",
    "name": "Solid Wood - Vintage Walnut",
    "size": "10\"",
    "type": "Tabletop",
    "price": 26,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-04-STAND",
    "imageSku": "IMG-S3-T1-04-STAND",
    "name": "Solid Wood - Vintage Walnut",
    "size": "A4",
    "type": "Tabletop",
    "price": 30,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t1",
    "sku": "MFR-S3-T1-03-STAND",
    "imageSku": "IMG-S3-T1-03-STAND",
    "name": "Solid Wood - Vintage Walnut",
    "size": "A3",
    "type": "Tabletop",
    "price": 39,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-06-STAND",
    "imageSku": "IMG-S3-T2-06-STAND",
    "name": "Solid Wood - Warm Walnut",
    "size": "6\"",
    "type": "Tabletop",
    "price": 14,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-07-STAND",
    "imageSku": "IMG-S3-T2-07-STAND",
    "name": "Solid Wood - Warm Walnut",
    "size": "7\"",
    "type": "Tabletop",
    "price": 18,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-08-STAND",
    "imageSku": "IMG-S3-T2-08-STAND",
    "name": "Solid Wood - Warm Walnut",
    "size": "8\"",
    "type": "Tabletop",
    "price": 20,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-10-STAND",
    "imageSku": "IMG-S3-T2-10-STAND",
    "name": "Solid Wood - Warm Walnut",
    "size": "10\"",
    "type": "Tabletop",
    "price": 26,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-04-STAND",
    "imageSku": "IMG-S3-T2-04-STAND",
    "name": "Solid Wood - Warm Walnut",
    "size": "A4",
    "type": "Tabletop",
    "price": 30,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t2",
    "sku": "MFR-S3-T2-03-STAND",
    "imageSku": "IMG-S3-T2-03-STAND",
    "name": "Solid Wood - Warm Walnut",
    "size": "A3",
    "type": "Tabletop",
    "price": 39,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-06-STAND",
    "imageSku": "IMG-S3-T3-06-STAND",
    "name": "Fresh Light Wheat",
    "size": "6\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-07-STAND",
    "imageSku": "IMG-S3-T3-07-STAND",
    "name": "Fresh Light Wheat",
    "size": "7\"",
    "type": "Tabletop",
    "price": 14,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-08-STAND",
    "imageSku": "IMG-S3-T3-08-STAND",
    "name": "Fresh Light Wheat",
    "size": "8\"",
    "type": "Tabletop",
    "price": 18,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-10-STAND",
    "imageSku": "IMG-S3-T3-10-STAND",
    "name": "Fresh Light Wheat",
    "size": "10\"",
    "type": "Tabletop",
    "price": 26,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-04-STAND",
    "imageSku": "IMG-S3-T3-04-STAND",
    "name": "Fresh Light Wheat",
    "size": "A4",
    "type": "Tabletop",
    "price": 30,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t3",
    "sku": "MFR-S3-T3-03-STAND",
    "imageSku": "IMG-S3-T3-03-STAND",
    "name": "Fresh Light Wheat",
    "size": "A3",
    "type": "Tabletop",
    "price": 39,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-06-STAND",
    "imageSku": "IMG-S3-T4-06-STAND",
    "name": "Roasted Tea",
    "size": "6\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-07-STAND",
    "imageSku": "IMG-S3-T4-07-STAND",
    "name": "Roasted Tea",
    "size": "7\"",
    "type": "Tabletop",
    "price": 14,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-08-STAND",
    "imageSku": "IMG-S3-T4-08-STAND",
    "name": "Roasted Tea",
    "size": "8\"",
    "type": "Tabletop",
    "price": 18,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-10-STAND",
    "imageSku": "IMG-S3-T4-10-STAND",
    "name": "Roasted Tea",
    "size": "10\"",
    "type": "Tabletop",
    "price": 26,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-04-STAND",
    "imageSku": "IMG-S3-T4-04-STAND",
    "name": "Roasted Tea",
    "size": "A4",
    "type": "Tabletop",
    "price": 30,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t4",
    "sku": "MFR-S3-T4-03-STAND",
    "imageSku": "IMG-S3-T4-03-STAND",
    "name": "Roasted Tea",
    "size": "A3",
    "type": "Tabletop",
    "price": 39,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-06-STAND",
    "imageSku": "IMG-S3-T5-06-STAND",
    "name": "Black Walnut",
    "size": "6\"",
    "type": "Tabletop",
    "price": 13,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-07-STAND",
    "imageSku": "IMG-S3-T5-07-STAND",
    "name": "Black Walnut",
    "size": "7\"",
    "type": "Tabletop",
    "price": 14,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-08-STAND",
    "imageSku": "IMG-S3-T5-08-STAND",
    "name": "Black Walnut",
    "size": "8\"",
    "type": "Tabletop",
    "price": 18,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-10-STAND",
    "imageSku": "IMG-S3-T5-10-STAND",
    "name": "Black Walnut",
    "size": "10\"",
    "type": "Tabletop",
    "price": 26,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-04-STAND",
    "imageSku": "IMG-S3-T5-04-STAND",
    "name": "Black Walnut",
    "size": "A4",
    "type": "Tabletop",
    "price": 30,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  },
  {
    "subcategoryKey": "s3-t5",
    "sku": "MFR-S3-T5-03-STAND",
    "imageSku": "IMG-S3-T5-03-STAND",
    "name": "Black Walnut",
    "size": "A3",
    "type": "Tabletop",
    "price": 39,
    "color": "",
    "craftsmanship": "",
    "photoIncluded": "",
    "material": "",
    "description": ""
  }
];

export function getProductsForSubcategory(subcategoryKey: string) {
  return shopProducts.filter((product) => product.subcategoryKey === subcategoryKey);
}
